In [0]:
# Tensorflow 개념

In [0]:
import tensorflow as tf

In [0]:
print(tf.__version__)

1.14.0


In [0]:
hello = tf.constant("Hello, Tensorflow")
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [0]:
print(type(hello))

<class 'tensorflow.python.framework.ops.Tensor'>


In [0]:
num1=tf.constant(10)
num2=tf.constant(20)

num3=tf.add(num1,num2)
print(num3)

Tensor("Add:0", shape=(), dtype=int32)


In [0]:
tensor = tf.constant(-1.0, shape=[2, 3]) #2 by 3
print(tensor)

print("\n")

sess=tf.Session()
print(sess.run(tensor))

Tensor("Const_8:0", shape=(2, 3), dtype=float32)


[[-1. -1. -1.]
 [-1. -1. -1.]]


In [0]:
## 세션 연결 후, run을 통해 실행
hello = tf.constant("Hello, Tensorflow")

sess = tf.Session()
print(sess.run(hello))

b'Hello, Tensorflow'


In [0]:
##텐서 플로워의 자료형

#플레이스 홀더 : 나중에 값을 입력받기 위한 사용되는 매개변수(parameter)

#shape(?,3)은 두번째 차원 요소가 3이고, 앞의 차원은 나중에 지정.

In [0]:
#None은 크기지정ㄴㄴ

tensorX=tf.placeholder(tf.float32, [None,2])

x_data=[[1,1],[2,2]]


In [0]:
sess = tf.Session()
sess.run(tf.global_variables_initializer()) #초기화

In [0]:
print(sess.run(tensorX, feed_dict={tensorX:x_data}))
sess.close()

[[1. 1.]
 [2. 2.]]


In [0]:
# tf.random_normal : 정규 분포로부터 랜덤한 값 생성

In [0]:
##행렬 연산

#Y = X (2행2열) * W(2행2열) + b(2행)

In [0]:
tensorX=tf.placeholder(tf.float32,[None,2])


W = tf.Variable(tf.random_normal([2,2]))  #2 by 2
b = tf.Variable(tf.random_normal([2,1]))  #2 by 1

print(W)
print(b)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32_ref>
<tf.Variable 'Variable_1:0' shape=(2, 1) dtype=float32_ref>


In [0]:
y = tf.matmul(tensorX, W) + b

In [0]:
sess=tf.Session()
sess.run(tf.global_variables_initializer())

In [0]:
print("x_data = ",x_data)
print("\n")
print("W = ", sess.run(W))
print("\n")
print("b = ", sess.run(b))
print("\n")

print("y = x_data * W + b = ", sess.run(y, feed_dict={tensorX:x_data}))

sess.close()

x_data =  [[1, 1], [2, 2]]


W =  [[-1.3142548   0.50986475]
 [ 0.99663854  0.8556536 ]]


b =  [[2.138163 ]
 [0.9133519]]


y = x_data * W + b =  [[1.8205469  3.5036814 ]
 [0.27811944 3.6443887 ]]


In [0]:
## tensorflow로 모델 만들고 예측

In [0]:
import tensorflow as tf

In [0]:
mnist=tf.keras.datasets.mnist
print(mnist)

<module 'tensorflow.python.keras.api._v1.keras.datasets.mnist' from '/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/api/_v1/keras/datasets/mnist/__init__.py'>


In [0]:
(x_train,y_train),(x_test, y_test)= mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [0]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


In [0]:
y_train[0:3]

array([5, 0, 4], dtype=uint8)

In [0]:
#값의 정규화

#Dropout, 값의 정규화 (0~1)

x_train,x_test=x_train/255.0, x_test/255.0

In [0]:
#Building the tf model

model=tf.keras.models.Sequential([tf.keras.layers.Flatten(input_shape=(28,28)), #2차원을 1차원으로 만들기
                                 tf.keras.layers.Dense(512, activation=tf.nn.relu),  #은닉층 512개 #ReLU 함수 : 0이하를 잘라버림. 0이하는 0으로 만들어줌   => y_axis=[0 , )
                                  tf.keras.layers.Dropout(0.2), #20% 버리기  #과적합 해결하기 위해
                                  tf.keras.layers.Dense(10, activation=tf.nn.softmax)]) #softmax : 확률로 만들어 이를 다 더하면 1이 된다.

In [0]:
#모델 학습과정 설정하기
model.compile(optimizer='adam', #손실이 적은 값을 만들어주는 것을 최적화라 하고 optimizer는 최적화를 만들어 주는 코드
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [0]:
#모델 학습
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
60000/60000 [==============================] - 7s 121us/sample - loss: 0.2187 - acc: 0.9363
Epoch 2/5
60000/60000 [==============================] - 7s 112us/sample - loss: 0.0962 - acc: 0.9712
Epoch 3/5
60000/60000 [==============================] - 7s 112us/sample - loss: 0.0696 - acc: 0.9779
Epoch 4/5
60000/60000 [==============================] - 7s 113us/sample - loss: 0.0550 - acc: 0.9830
Epoch 5/5
60000/60000 [==============================] - 7s 114us/sample - loss: 0.0432 - acc: 0.9862


In [0]:
#평가

model.evaluate(x_test,y_test)

10000/10000 [==============================] - 1s 71us/sample - loss: 0.0640 - acc: 0.9791


[0.06401209493269562, 0.9791]