In [4]:
xarr=np.array([1.1,1.2,1.3,1.4,1.5])
yarr=np.array([2.1,2.2,2.3,2.4,2.5])
cond=np.array([True,False,True,True,False])

In [7]:
result=[(x if c else y)
       for x,y,c in zip(xarr,yarr,cond)]

In [3]:
from IPython.display import Image 
from numpy.random import randn
import numpy as np

In [10]:
arr=randn(4,4)
arr

array([[ 1.30007809, -0.31561092,  0.94066652,  1.02852204],
       [-1.0115181 , -0.60039679, -1.36870149,  0.87441584],
       [ 0.27846906, -0.50632523, -0.740887  ,  1.1624545 ],
       [-0.88578758, -0.64113823, -0.84766983,  1.86655725]])

In [11]:
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [13]:
np.where(arr>0,True,False)

array([[ True, False,  True,  True],
       [False, False, False,  True],
       [ True, False, False,  True],
       [False, False, False,  True]])

In [14]:
np.where(arr>0,2,arr)

array([[ 2.        , -0.31561092,  2.        ,  2.        ],
       [-1.0115181 , -0.60039679, -1.36870149,  2.        ],
       [ 2.        , -0.50632523, -0.740887  ,  2.        ],
       [-0.88578758, -0.64113823, -0.84766983,  2.        ]])

In [16]:
arr=np.random.randn(5,4)

In [17]:
arr

array([[ 0.74379225, -0.23867118, -1.87765811,  1.07138491],
       [-0.53514572,  0.72347531, -1.70370783, -0.93796121],
       [-0.16243181, -1.1710476 , -1.14233013,  0.51821598],
       [-0.70432686, -1.6155297 ,  0.73295916,  0.54109946],
       [-0.78482908,  0.32621733,  1.53589959,  0.01046049]])

In [18]:
arr.mean()

-0.23350673810898956

In [20]:
np.mean(arr)

-0.23350673810898956

In [21]:
arr.sum()

-4.670134762179791

In [22]:
np.sum(arr)

-4.670134762179791

In [24]:
arr.mean(axis=1)  #axis=0 은 행을 표현, #axis=1은 열을 표현

array([-0.07528803, -0.61333487, -0.48939839, -0.26144948,  0.27193708])

In [26]:
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
arr.cumsum(0) #누적합   #arr=(list1,list2,liat3)  
#arr.cumsum(0)=(list1,list1+list2,list1+list2+list3)   #0은 행

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [29]:
arr.cumsum(1) #1은 열

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

In [28]:
arr.cumprod(1) #누적곱 

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [34]:
arr=randn(100)
arr

array([ 1.22873968, -0.41755508,  0.72529784,  1.44453015,  1.05343019,
        0.2469933 ,  1.56287023,  0.88127532, -0.65374025, -0.05837101,
       -0.3394111 , -0.87713552,  0.42087837,  0.38377357, -0.05397716,
       -0.0230313 , -2.6798533 ,  0.23919631, -0.22015469,  0.51525145,
        1.29731899,  0.64495696,  1.20605019,  1.31036399,  0.34677814,
        0.7008645 , -1.08592719, -0.94155782,  1.97131462, -0.17352688,
        0.38692511, -1.21390294,  1.50588632, -0.71627928, -1.26846379,
       -0.25238407,  1.80651745,  1.70725057, -1.50563217,  0.05040798,
        0.1037878 , -0.28667648,  0.43392061, -0.90533997, -0.63452755,
       -0.45712205, -0.30508748,  1.38379454,  0.69853884,  1.86511337,
       -0.96195327,  0.01781805, -0.66888757,  1.26163454,  0.95107921,
        0.3866804 ,  0.45162256, -0.85228127, -1.3993393 ,  0.58675862,
        0.40486522,  1.16663126,  0.54180111,  1.35611101,  1.48601504,
       -0.86272983,  1.71792662, -0.16240443,  1.08598142,  0.74

In [35]:
(arr>0).sum()

56

In [38]:
bools=np.array([False,False,True,False])
bools

array([False, False,  True, False])

In [39]:
bools.any()

True

In [41]:
bools.all()

False

In [42]:
arr=randn(8)
arr

array([ 0.39868781,  0.29812539, -0.48225319,  0.51919831, -1.14150323,
        1.6216198 , -0.40510568,  0.6229508 ])

In [43]:
arr.sort() #오름차순

In [44]:
arr

array([-1.14150323, -0.48225319, -0.40510568,  0.29812539,  0.39868781,
        0.51919831,  0.6229508 ,  1.6216198 ])

In [45]:
arr=randn(3,4)
arr

array([[ 0.16023149, -1.19331273,  0.36464955,  1.01175882],
       [-1.23148801,  1.32837494, -0.37210974, -0.36306212],
       [ 0.48666775,  0.07826091,  0.77088937,  0.75820166]])

In [48]:
arr.sort(1)
arr

array([[-1.19331273,  0.16023149,  0.36464955,  1.01175882],
       [-1.23148801, -0.37210974, -0.36306212,  1.32837494],
       [ 0.07826091,  0.48666775,  0.75820166,  0.77088937]])

In [49]:
big=randn(100)
big

array([ 1.08595830e+00, -1.06431735e+00, -6.82755929e-01, -7.86235657e-01,
       -5.66080401e-01, -6.39086799e-01, -2.65699881e-01,  1.00761458e+00,
       -8.31400474e-02, -4.70682659e-01,  1.30321802e+00, -1.25526820e-01,
       -2.81607855e-01,  5.27645853e-01, -1.80567539e+00, -1.12093926e+00,
        1.72727969e+00,  1.84540428e+00,  6.21842098e-01, -1.45243711e+00,
        8.66495739e-02,  1.69107072e+00,  2.21653596e-03, -2.27362916e-01,
        1.33314697e+00,  1.92834891e+00,  3.07782434e-01, -2.66104114e+00,
        2.80041790e-01,  1.16673730e-01,  3.47554338e-01,  1.96307573e+00,
       -5.27800262e-01,  1.28979439e+00, -3.32947101e+00, -8.12793440e-01,
       -8.92013502e-01, -4.94523915e-01,  1.28937166e+00, -8.29699436e-01,
       -5.13458345e-01, -9.42384752e-01, -7.78262058e-01,  5.39516237e-01,
       -2.96270208e-01,  4.28684585e-01,  1.28177589e+00,  5.20094308e-01,
       -1.42974028e+00, -1.43276271e+00,  6.86626993e-01,  1.29323026e+00,
        4.18843447e-01,  

In [50]:
big.sort()
big

array([-3.32947101e+00, -2.66104114e+00, -1.91281868e+00, -1.88305047e+00,
       -1.80567539e+00, -1.73630726e+00, -1.72850841e+00, -1.71948786e+00,
       -1.62581986e+00, -1.45243711e+00, -1.43276271e+00, -1.42974028e+00,
       -1.23988275e+00, -1.12093926e+00, -1.06431735e+00, -9.89395861e-01,
       -9.42384752e-01, -8.92013502e-01, -8.60665036e-01, -8.29699436e-01,
       -8.28760298e-01, -8.18327946e-01, -8.12793440e-01, -7.86235657e-01,
       -7.78915065e-01, -7.78262058e-01, -7.77156307e-01, -7.09173669e-01,
       -6.82755929e-01, -6.41962436e-01, -6.39086799e-01, -5.66080401e-01,
       -5.54051152e-01, -5.43441038e-01, -5.27800262e-01, -5.13458345e-01,
       -4.96991419e-01, -4.94523915e-01, -4.70682659e-01, -4.16002410e-01,
       -2.96270208e-01, -2.81607855e-01, -2.65699881e-01, -2.27362916e-01,
       -2.23576418e-01, -1.49421997e-01, -1.25526820e-01, -9.21487303e-02,
       -8.31400474e-02, -6.11404691e-02,  2.21653596e-03,  7.51030605e-02,
        8.66495739e-02,  

In [52]:
big[int(0.05*len(big))]  #len(big)=100  #100*0.05=5  #big의 5+1=6번째 원소 big[5]

-1.7363072624857017

In [55]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe'], dtype='<U4')

In [57]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [58]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [59]:
int=np.array([3,3,3,4,2,2,2,1,1,1,1])

In [61]:
np.unique(int)

array([1, 2, 3, 4])

In [63]:
np.in1d(int,[1,4])

array([False, False, False,  True, False, False, False,  True,  True,
        True,  True])

## pandas

In [64]:
from IPython.display import Image 

from pandas import Series, DataFrame
import pandas as pd
import numpy as np

In [65]:
a=Series([4,-7,32,8])

In [66]:
a   #0,1,2,3  은 index

0     4
1    -7
2    32
3     8
dtype: int64

In [67]:
a.index

RangeIndex(start=0, stop=4, step=1)

In [68]:
a.values

array([ 4, -7, 32,  8], dtype=int64)

In [69]:
a2=Series([1,2,3,4],index=["a","b","c","d"])

In [70]:
a2

a    1
b    2
c    3
d    4
dtype: int64

In [72]:
a2['a']

1

In [74]:
a2['d']=12
a2[['c','d']]

c     3
d    12
dtype: int64

In [75]:
a2

a     1
b     2
c     3
d    12
dtype: int64

In [76]:
a2**2

a      1
b      4
c      9
d    144
dtype: int64

In [77]:
'd' in a2

True

In [78]:
'r' in a2

False

In [79]:
np.exp(a2)  #지수e 함수 exponential func

a         2.718282
b         7.389056
c        20.085537
d    162754.791419
dtype: float64

In [81]:
fruit={'apple':3,'orange':6, 'strewberry':7}
a=Series(fruit)
a

apple         3
orange        6
strewberry    7
dtype: int64

In [82]:
table=['apple','orange','grape']
a2=Series(fruit,index=table)
a2

apple     3.0
orange    6.0
grape     NaN
dtype: float64

In [83]:
pd.isnull(a2)

apple     False
orange    False
grape      True
dtype: bool

In [85]:
a2.isnull()

apple     False
orange    False
grape      True
dtype: bool

In [84]:
pd.notnull(a2)

apple      True
orange     True
grape     False
dtype: bool

In [89]:
a3=a+a2

In [90]:
a3.name='fruit on the table'
a3.index.name='fruit'

In [91]:
a3

fruit
apple          6.0
grape          NaN
orange        12.0
strewberry     NaN
Name: fruit on the table, dtype: float64

In [92]:
a3.index=[1,2,3,4]
a3

1     6.0
2     NaN
3    12.0
4     NaN
Name: fruit on the table, dtype: float64

## DataFrame
표 같은 스프레드시트 형식의 자료구조로 여러개의 칼럼을 가진다.
각 칼럼은 서로 다른 종류의 값(숫자, 문자, 불리언 등)을 담을 수 있다.
로우와 칼럼에 대한 Index가 있는데, Index의 모양이 같은 Series 객체를 담고 있는 파이썬 사전으로 생각하자.
Dataframe은 데이터를 내부적으로 2차원 형식으로 저장
고차원의 표 형식 데이터를 계층적 색인(Hierarchical Indexing)을 통해 쉽게 표현할 수 있다. </font>

In [138]:
data={'state':['Ohio','Ohio',"ohio",'nihao','nihao'],
     'year':[2000,2001,2002,2003,2001],
     'pop':[1,2,3,4,5]}
frame=DataFrame(data)


In [139]:
frame

state  year  pop
0   Ohio  2000    1
1   Ohio  2001    2
2   ohio  2002    3
3  nihao  2003    4
4  nihao  2001    5

In [140]:
DataFrame(data,columns=['year','state','pop'])
#순서


year  state  pop
0  2000   Ohio    1
1  2001   Ohio    2
2  2002   ohio    3
3  2003  nihao    4
4  2001  nihao    5

In [141]:
frame2=DataFrame(data,columns=['year','state','pop','debt'],
                index=[1,2,3,4,5])
frame2

year  state  pop debt
1  2000   Ohio    1  NaN
2  2001   Ohio    2  NaN
3  2002   ohio    3  NaN
4  2003  nihao    4  NaN
5  2001  nihao    5  NaN

In [142]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [143]:
frame2.state

1     Ohio
2     Ohio
3     ohio
4    nihao
5    nihao
Name: state, dtype: object

In [144]:
frame2.ix[3]

C:\Users\202-006\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


year     2002
state    ohio
pop         3
debt      NaN
Name: 3, dtype: object

In [145]:
frame2.loc[3]

year     2002
state    ohio
pop         3
debt      NaN
Name: 3, dtype: object

In [146]:
frame2.iloc[2]

year     2002
state    ohio
pop         3
debt      NaN
Name: 3, dtype: object

In [147]:
frame2['debt']=2.3
frame2

year  state  pop  debt
1  2000   Ohio    1   2.3
2  2001   Ohio    2   2.3
3  2002   ohio    3   2.3
4  2003  nihao    4   2.3
5  2001  nihao    5   2.3

In [148]:
frame2['debt']=np.arange(5.)   #np.arange(5.) 소수점
frame2

year  state  pop  debt
1  2000   Ohio    1   0.0
2  2001   Ohio    2   1.0
3  2002   ohio    3   2.0
4  2003  nihao    4   3.0
5  2001  nihao    5   4.0

In [149]:
frame2['debt']=np.arange(5)  
frame2

year  state  pop  debt
1  2000   Ohio    1     0
2  2001   Ohio    2     1
3  2002   ohio    3     2
4  2003  nihao    4     3
5  2001  nihao    5     4

In [150]:
frame2['debt']=np.arange(5.0)  
frame2

year  state  pop  debt
1  2000   Ohio    1   0.0
2  2001   Ohio    2   1.0
3  2002   ohio    3   2.0
4  2003  nihao    4   3.0
5  2001  nihao    5   4.0

In [151]:
val = Series([-1.2, -1.5, -1.7], index=[2,4,5])
frame2['debt'] = val
frame2

year  state  pop  debt
1  2000   Ohio    1   NaN
2  2001   Ohio    2  -1.2
3  2002   ohio    3   NaN
4  2003  nihao    4  -1.5
5  2001  nihao    5  -1.7

In [152]:
frame2['T or F']=frame2.state=='Ohio'
frame2

year  state  pop  debt  T or F
1  2000   Ohio    1   NaN    True
2  2001   Ohio    2  -1.2    True
3  2002   ohio    3   NaN   False
4  2003  nihao    4  -1.5   False
5  2001  nihao    5  -1.7   False

In [158]:
pop={'nihao':{2001:2.3,2002:2.4},
    'ohio':{2000:1.1,2001:1.5,2002:3.6}}
frame3=DataFrame(pop)

In [159]:
frame3

nihao  ohio
2000    NaN   1.1
2001    2.3   1.5
2002    2.4   3.6

In [160]:
frame3.T #전치행렬T

2000  2001  2002
nihao   NaN   2.3   2.4
ohio    1.1   1.5   3.6

In [161]:
DataFrame(pop,index=[2001,2002,2003])

nihao  ohio
2001    2.3   1.5
2002    2.4   3.6
2003    NaN   NaN

In [162]:
frame3

nihao  ohio
2000    NaN   1.1
2001    2.3   1.5
2002    2.4   3.6

In [163]:
pdata={'ohio':frame3['ohio'][:-1],'nihao':frame3['nihao'][:2]}

In [164]:
DataFrame(pdata)

ohio  nihao
2000   1.1    NaN
2001   1.5    2.3

In [165]:
frame3.index.name='year';frame3.columns.name='state'
frame3

state  nihao  ohio
year              
2000     NaN   1.1
2001     2.3   1.5
2002     2.4   3.6

In [166]:
frame3.values

array([[nan, 1.1],
       [2.3, 1.5],
       [2.4, 3.6]])

In [167]:
a=Series(range(3),index=['a','b','c'])
index=a.index
index

Index(['a', 'b', 'c'], dtype='object')

In [168]:
index[1:]

Index(['b', 'c'], dtype='object')

In [169]:
index=pd.Index(np.arange(3))
a2=Series([1.5,-2.5,0],index=index)
a2.index is index

True

In [170]:
frame3

state  nihao  ohio
year              
2000     NaN   1.1
2001     2.3   1.5
2002     2.4   3.6

In [171]:
'ohio' in frame3.columns

True

In [172]:
2003 in frame3.index

False

In [173]:
a=Series([1.2,4.5,-2.3,1.1],index=['d','c','a','b'])
a

d    1.2
c    4.5
a   -2.3
b    1.1
dtype: float64

In [174]:
a2=a.reindex(['a','b','c','d','e','f'])
a2

a   -2.3
b    1.1
c    4.5
d    1.2
e    NaN
f    NaN
dtype: float64

In [176]:
a.reindex(['a','b','c','d','e','f'],fill_value=0)

a   -2.3
b    1.1
c    4.5
d    1.2
e    0.0
f    0.0
dtype: float64

In [179]:
a3=Series(['blue','purple','yellow'],index=[0,3,5])
a3.reindex(range(7),method='bfill')

0      blue
1    purple
2    purple
3    purple
4    yellow
5    yellow
6       NaN
dtype: object

In [218]:
frame=DataFrame(np.arange(9).reshape((3,3)),
               index=['a','b','c'],
               columns=['Ohio', 'Texas', 'California'])

In [219]:
frame

Ohio  Texas  California
a     0      1           2
b     3      4           5
c     6      7           8

In [220]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   3.0    4.0         5.0
c   6.0    7.0         8.0
d   NaN    NaN         NaN

In [194]:
frame2

year  state  pop  debt  T or F
1  2000   Ohio    1   NaN    True
2  2001   Ohio    2  -1.2    True
3  2002   ohio    3   NaN   False
4  2003  nihao    4  -1.5   False
5  2001  nihao    5  -1.7   False

In [221]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states) #reindex 추가 생성

Texas  Utah  California
a      1   NaN           2
b      4   NaN           5
c      7   NaN           8

In [222]:
frame.reindex(index=['a', 'b', 'c', 'd'], columns=states)

Texas  Utah  California
a    1.0   NaN         2.0
b    4.0   NaN         5.0
c    7.0   NaN         8.0
d    NaN   NaN         NaN

In [195]:
a=Series(np.arange(5.),index=['a','b','c','d','e'])

In [196]:
new_a=a.drop('c')

In [198]:
new_a

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [200]:
a.drop(['a','c'])

b    1.0
d    3.0
e    4.0
dtype: float64

In [201]:
a

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [203]:
data=DataFrame(np.arange(16).reshape((4,4)),
              index=['ohio','colrado','utah','NewYork'],
              columns=[1,2,3,4])

In [204]:
data

1   2   3   4
ohio      0   1   2   3
colrado   4   5   6   7
utah      8   9  10  11
NewYork  12  13  14  15

In [205]:
data.drop(["NewYork",'ohio'])

1  2   3   4
colrado  4  5   6   7
utah     8  9  10  11

In [206]:
data.drop(2,axis=1)

1   3   4
ohio      0   2   3
colrado   4   6   7
utah      8  10  11
NewYork  12  14  15

In [207]:
data.drop([2,3],axis=1)

1   4
ohio      0   3
colrado   4   7
utah      8  11
NewYork  12  15

In [208]:
a=Series(np.arange(4.),index=['a','b','c','d'])
a

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [209]:
a['b']

1.0

In [210]:
a[1] #1은 b의 위치

1.0

In [211]:
a[2:4]

c    2.0
d    3.0
dtype: float64

In [212]:
a[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [213]:
a[[1,3]]

b    1.0
d    3.0
dtype: float64

In [215]:
a['b':'c'] #라벨이름으로 슬라이싱 할 경우, 끝점도 포함한다.


b    1.0
c    2.0
dtype: float64

In [216]:
a['b':'c']=6
a

a    0.0
b    6.0
c    6.0
d    3.0
dtype: float64

In [214]:
a[a<2]

a    0.0
b    1.0
dtype: float64

In [225]:
data=DataFrame(np.arange(16).reshape((4,4)),
              index=['ohio','colorado','newyork','utah'],
              columns=['1','2','3','4'])

In [226]:
data

1   2   3   4
ohio       0   1   2   3
colorado   4   5   6   7
newyork    8   9  10  11
utah      12  13  14  15

In [227]:
data['2']

ohio         1
colorado     5
newyork      9
utah        13
Name: 2, dtype: int32

In [229]:
data[['3','1']]

3   1
ohio       2   0
colorado   6   4
newyork   10   8
utah      14  12

In [230]:
data[:2]

1  2  3  4
ohio      0  1  2  3
colorado  4  5  6  7

In [231]:
data[data['3']>5]

1   2   3   4
colorado   4   5   6   7
newyork    8   9  10  11
utah      12  13  14  15

In [232]:
data<5

1      2      3      4
ohio       True   True   True   True
colorado   True  False  False  False
newyork   False  False  False  False
utah      False  False  False  False

In [233]:
data[data<5]=0
data

1   2   3   4
ohio       0   0   0   0
colorado   0   5   6   7
newyork    8   9  10  11
utah      12  13  14  15

In [235]:
data.loc['colorado', ['2', '3']]

2    5
3    6
Name: colorado, dtype: int32

In [241]:
data.ix[['colorado','utah'],[3,0,1]]

C:\Users\202-006\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


4   1   2
colorado   7   0   5
utah      15  12  13

In [243]:
data.iloc[[1,3], [3, 0, 1]]

4   1   2
colorado   7   0   5
utah      15  12  13

In [245]:
data.loc[['colorado','utah'],['4','1','2']]

4   1   2
colorado   7   0   5
utah      15  12  13

In [246]:
s1=Series([7.5,7.6,3.7,-9.3], index=['a','c','d','e'])

In [248]:
s2=Series([-1.1,2.3,6.4,6,-5.9], index=['a','c','e','f','g'])

In [249]:
s1

a    7.5
c    7.6
d    3.7
e   -9.3
dtype: float64

In [250]:
s2

a   -1.1
c    2.3
e    6.4
f    6.0
g   -5.9
dtype: float64

In [251]:
s1+s2

a    6.4
c    9.9
d    NaN
e   -2.9
f    NaN
g    NaN
dtype: float64

In [255]:
df1=DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),
             index=['ohio','texas','colorado'])

In [256]:
df2=DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),
             index=['utah','ohio','texas','oregon'])

In [257]:
df1

b    c    d
ohio      0.0  1.0  2.0
texas     3.0  4.0  5.0
colorado  6.0  7.0  8.0

In [258]:
df2

b     d     e
utah    0.0   1.0   2.0
ohio    3.0   4.0   5.0
texas   6.0   7.0   8.0
oregon  9.0  10.0  11.0

In [259]:
df1+df2

b   c     d   e
colorado  NaN NaN   NaN NaN
ohio      3.0 NaN   6.0 NaN
oregon    NaN NaN   NaN NaN
texas     9.0 NaN  12.0 NaN
utah      NaN NaN   NaN NaN

In [260]:
df1=DataFrame(np.arange(12.).reshape((3,4)),columns=list('abcd'))
df2=DataFrame(np.arange(20.).reshape((4,5)),columns=list('abcde'))

In [261]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [262]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [265]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [266]:
df1.reindex(columns=df2.columns,fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [267]:
arr=np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [268]:
arr[0]

array([0., 1., 2., 3.])

In [269]:
arr-arr[1]

array([[-4., -4., -4., -4.],
       [ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.]])

In [275]:
frame=DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),
               index=['utah','ohio','texas','oregon'])
frame

b     d     e
utah    0.0   1.0   2.0
ohio    3.0   4.0   5.0
texas   6.0   7.0   8.0
oregon  9.0  10.0  11.0

In [276]:
series=frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: utah, dtype: float64

In [277]:
frame-series

b    d    e
utah    0.0  0.0  0.0
ohio    3.0  3.0  3.0
texas   6.0  6.0  6.0
oregon  9.0  9.0  9.0

In [282]:
series1=frame['d']
series1

utah       1.0
ohio       4.0
texas      7.0
oregon    10.0
Name: d, dtype: float64

In [283]:
frame.sub(series1, axis=0) #빼기

b    d    e
utah   -1.0  0.0  1.0
ohio   -1.0  0.0  1.0
texas  -1.0  0.0  1.0
oregon -1.0  0.0  1.0

##  Function application and mapping 
함수 적용과 매핑

pandas 객체에도 NumPy의 유니버설 함수를 적용할 수 있다.
유니버설 함수 : 배열의 각 원소에 적용되는 메소드

In [285]:
frame=DataFrame(np.random.randn(4,3),columns=list('bde'),
               index=['utah','ohio','texas','oregon'])

In [286]:
frame

b         d         e
utah   -0.311306 -0.801334  1.591556
ohio   -0.070124 -1.363656  0.312304
texas  -1.444448  0.726685 -1.197495
oregon  1.185579 -0.628650 -1.512128

In [287]:
np.abs(frame)

b         d         e
utah    0.311306  0.801334  1.591556
ohio    0.070124  1.363656  0.312304
texas   1.444448  0.726685  1.197495
oregon  1.185579  0.628650  1.512128

In [288]:
f=lambda x:x.max()-x.min()

frame.apply(f)

b    2.630026
d    2.090341
e    3.103684
dtype: float64

In [290]:
f1=lambda x:x.max()

frame.apply(f1)

b    1.185579
d    0.726685
e    1.591556
dtype: float64

In [291]:
f2=lambda x:x.min()

frame.apply(f2)

b   -1.444448
d   -1.363656
e   -1.512128
dtype: float64

In [289]:
frame.apply(f,axis=1)

utah      2.392891
ohio      1.675960
texas     2.171133
oregon    2.697707
dtype: float64

In [292]:
def f(x):
    return Series([x.min(), x.max()], index=['min', 'max'])

frame.apply(f)

b         d         e
min -1.444448 -1.363656 -1.512128
max  1.185579  0.726685  1.591556

In [293]:
# 실수값을 문자열 포맷으로 변환
format = lambda x: '%.2f' % x
frame.applymap(format)

b      d      e
utah    -0.31  -0.80   1.59
ohio    -0.07  -1.36   0.31
texas   -1.44   0.73  -1.20
oregon   1.19  -0.63  -1.51

In [294]:
frame['e'].map(format)

utah       1.59
ohio       0.31
texas     -1.20
oregon    -1.51
Name: e, dtype: object

In [295]:
a=Series([4,6,-7,2])

In [296]:
a.sort_values()

2   -7
3    2
0    4
1    6
dtype: int64

In [297]:
a=Series([4,6,np.nan,-7,np.nan,2])

In [298]:
a.sort_values()

3   -7.0
5    2.0
0    4.0
1    6.0
2    NaN
4    NaN
dtype: float64

In [305]:
frame=DataFrame({'b':[4,7,6,9],"a":[3,3,4,4]})

In [306]:
frame

b  a
0  4  3
1  7  3
2  6  4
3  9  4

In [307]:
frame.sort_values(by='b')

b  a
0  4  3
2  6  4
1  7  3
3  9  4

In [308]:
frame.sort_values(by=['a','b'])

b  a
0  4  3
1  7  3
2  6  4
3  9  4

In [309]:
a=Series([7,4,7,2,9,4,0])

In [310]:
a

0    7
1    4
2    7
3    2
4    9
5    4
6    0
dtype: int64

In [311]:
a.rank()

0    5.5
1    3.5
2    5.5
3    2.0
4    7.0
5    3.5
6    1.0
dtype: float64

In [313]:
a.rank(method='first') #순위가 작은수부터

0    5.0
1    3.0
2    6.0
3    2.0
4    7.0
5    4.0
6    1.0
dtype: float64

In [316]:
a.rank(ascending=False, method='max') #순위가 큰수 부터 #3,4순위가 같은 값일 때 둘다 4순위

0    3.0
1    5.0
2    3.0
3    6.0
4    1.0
5    5.0
6    7.0
dtype: float64

In [317]:
a.rank(ascending=True, method='max')#순위가 작은 수 부터 #3,4순위가 같은 값일 때 둘다 4순위

0    6.0
1    4.0
2    6.0
3    2.0
4    7.0
5    4.0
6    1.0
dtype: float64

In [318]:
a.rank(ascending=False, method='dense') #순위가 큰수 부터 #3,4순위가 같은 값일 때 둘다 3순위

0    2.0
1    3.0
2    2.0
3    4.0
4    1.0
5    3.0
6    5.0
dtype: float64

In [319]:
a.rank(ascending=True, method='dense')#순위가 작은 수 부터 #3,4순위가 같은 값일 때 둘다 3순위

0    4.0
1    3.0
2    4.0
3    2.0
4    5.0
5    3.0
6    1.0
dtype: float64

In [320]:
a=Series(range(5),index=['a','a','b','b','c'])
a

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [321]:
a.index.is_unique

False

In [322]:
a['a']

a    0
a    1
dtype: int64

In [324]:
a['c']

4

In [325]:
df = DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

0         1         2
a -1.043676  0.661402  1.179522
a -1.430671  0.100411 -1.619281
b -1.054132 -0.234600  1.432043
b  0.218228 -1.248528 -0.131352

In [326]:
df.loc['b']

0         1         2
b -1.054132 -0.234600  1.432043
b  0.218228 -1.248528 -0.131352