In [1]:
from IPython.display import Image 
from numpy.random import randn
import numpy as np

In [2]:
#Numpy 는 다차원 객체

In [4]:
data=randn(2,3)

In [5]:
data

array([[ 0.42378534,  0.97406031,  1.80068923],
       [ 2.30140854,  0.63378672, -2.14669549]])

In [6]:
data*10

array([[  4.23785345,   9.74060313,  18.00689227],
       [ 23.01408542,   6.33786724, -21.4669549 ]])

In [7]:
data+data

array([[ 0.84757069,  1.94812063,  3.60137845],
       [ 4.60281708,  1.26757345, -4.29339098]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

In [10]:
data1=[6,3.44,4.5,6]
arr1=np.array(data1)
arr1

array([6.  , 3.44, 4.5 , 6.  ])

In [12]:
data2=[[1,2,3,4],[5,6,7,8],[1,2,3,4]]
arr2=np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [14]:
arr2.ndim

2

In [15]:
arr2.shape

(3, 4)

In [18]:
np.zeros((11,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
a=np.empty((2,5,3))
#[Tip] np.empty 
#np.empty는 0으로 초기화된 배열을 반환하지 않는다. 
#대부분 empty는 초기화되지 않은 값으로 채워진 배열을 반환한다
a

array([[[1.12886542e-311, 9.58487353e-322, 0.00000000e+000],
        [0.00000000e+000, 2.31462030e-152, 5.02034658e+175],
        [1.77077036e-051, 2.85282897e-056, 1.93409960e-076],
        [2.19417761e-056, 1.47763641e+248, 1.16096346e-028],
        [7.69165785e+218, 1.35617292e+248, 6.38062304e+170]],

       [[1.79454378e-052, 2.59104570e+184, 3.77193740e-061],
        [4.26398666e-096, 6.32299154e+233, 6.48224638e+170],
        [5.22411352e+257, 5.74020278e+180, 8.37174974e-144],
        [1.41529402e+161, 9.16651763e-072, 4.10024125e+097],
        [3.22240420e-057, 3.41846037e+126, 2.47148134e-258]]])

In [22]:
a.ndim

3

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr1=np.array([1,2,3],dtype=np.float64)
arr1.dtype

dtype('float64')

In [27]:
arr2=np.array([1,2,3,4,5])
arr2.dtype

dtype('int32')

In [33]:
arr3=arr2.astype(np.int32)
arr3.dtype

dtype('int32')

[Tip] astype 
astype을 호출하면 새로운 dtype이 이전 dtype과 같아도 항상 새로운 배열을 생성(데이터를 복사)한다. 
float64나 float32 같은 부동소수점은 근사값이라는 사실을 염두에 두는게 중요하다.

In [37]:
arr=np.array([1,2,3,4,5])
# astype 을 사용하여 숫자로 변환
arr.astype(np.int32)

array([1, 2, 3, 4, 5])

In [38]:
arr

array([1, 2, 3, 4, 5])

In [39]:
arr.astype(np.float64)

array([1., 2., 3., 4., 5.])

In [42]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [45]:
arr=np.array([[1,2,3],[4,5,6]],dtype=np.float64)

arr

arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [48]:
arr=np.arange(10)

arr[5:9]

arr[5:8]=11
arr

array([ 0,  1,  2,  3,  4, 11, 11, 11,  8,  9])

In [49]:
arr_slice=arr[3:6]

arr_slice[1]=5432
arr

array([   0,    1,    2,    3, 5432,   11,   11,   11,    8,    9])

In [50]:
arr_slice[:]=11
arr

array([ 0,  1,  2, 11, 11, 11, 11, 11,  8,  9])

## 2차원

In [52]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [55]:
arr2d[2][0]

7

In [56]:
arr2d[2,0]

7

## 3차원

In [57]:
arr3d = np.array([[[1, 2, 3,4], [ 5, 6,7,8]], [[ 9,10,11,12], [13,14,15,16]]])
arr3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [58]:
arr3d[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [59]:
arr3d.copy()

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [60]:
arr3d[1].copy()

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [61]:
arr3d[1]=11
arr3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[11, 11, 11, 11],
        [11, 11, 11, 11]]])

In [62]:
arr3d[0,1,2]

7

In [63]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
arr2d[2:,:]

array([[7, 8, 9]])

In [76]:
arr2d[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [78]:
arr2d[:2,1:]=0

arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## Boolean indexing 

In [86]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

data=randn(7,2)

In [87]:
data

array([[ 0.26165441,  0.1996354 ],
       [ 0.35174266,  0.46129486],
       [-0.72441025, -0.46661306],
       [-2.93022086, -0.37679732],
       [ 1.92369948, -0.07571495],
       [-0.1833497 ,  0.0081288 ],
       [-0.68894832, -0.65385339]])

In [88]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

In [89]:
data[names=='Bob']

array([[ 0.26165441,  0.1996354 ],
       [-2.93022086, -0.37679732]])

In [90]:
data[names=='Joe',1:]

array([[ 0.46129486],
       [ 0.0081288 ],
       [-0.65385339]])

In [91]:
data[~(names=='Bob')]

array([[ 0.35174266,  0.46129486],
       [-0.72441025, -0.46661306],
       [ 1.92369948, -0.07571495],
       [-0.1833497 ,  0.0081288 ],
       [-0.68894832, -0.65385339]])

In [92]:
data[names!='Bob']

array([[ 0.35174266,  0.46129486],
       [-0.72441025, -0.46661306],
       [ 1.92369948, -0.07571495],
       [-0.1833497 ,  0.0081288 ],
       [-0.68894832, -0.65385339]])

In [93]:
a=(names!='Bob')|(names!='Joe')

In [94]:
a

array([ True,  True,  True,  True,  True,  True,  True])

In [95]:
data[a]

array([[ 0.26165441,  0.1996354 ],
       [ 0.35174266,  0.46129486],
       [-0.72441025, -0.46661306],
       [-2.93022086, -0.37679732],
       [ 1.92369948, -0.07571495],
       [-0.1833497 ,  0.0081288 ],
       [-0.68894832, -0.65385339]])

In [96]:
data[data>0]=0

data

array([[ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [-0.72441025, -0.46661306],
       [-2.93022086, -0.37679732],
       [ 0.        , -0.07571495],
       [-0.1833497 ,  0.        ],
       [-0.68894832, -0.65385339]])

In [97]:
data[names!='Bob']=3
data

array([[ 0.        ,  0.        ],
       [ 3.        ,  3.        ],
       [ 3.        ,  3.        ],
       [-2.93022086, -0.37679732],
       [ 3.        ,  3.        ],
       [ 3.        ,  3.        ],
       [ 3.        ,  3.        ]])

## Fancy indexing

-팬시 색인은 정수 배열을 사용한 색인을 설명하기 위해 NumPy에서 차용한 단어다.

In [106]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [107]:
arr = np.empty((8, 4))
arr[[4, -3, -2, 7]]

array([[4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [109]:
arr=np.arange(21).reshape((7,3))

In [110]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [111]:
#(1, 0), (5, 2), (4, 1), (2, 2) 에 대응하는 요소 선택

arr[[1,5,4,2],[0,2,1,2]]

array([ 3, 17, 13,  8])

In [112]:
arr[[1,5,4,2]][:,[0,2,1,2]]

array([[ 3,  5,  4,  5],
       [15, 17, 16, 17],
       [12, 14, 13, 14],
       [ 6,  8,  7,  8]])

In [115]:
arr[[1,5,4,2]][:2,[0,2,1,2]]

array([[ 3,  5,  4,  5],
       [15, 17, 16, 17]])

In [113]:
arr[np.ix_([1,5,4,2],[0,2,1,2])]

array([[ 3,  5,  4,  5],
       [15, 17, 16, 17],
       [12, 14, 13, 14],
       [ 6,  8,  7,  8]])

## Transposing arrays and swapping axes 


배열 전치와 축 바꾸기

배열 전치는 데이터를 복사하지 않고 데이터 모양이 바뀐 뷰를 반환하는 특별한 기능
ndarray는 transpose 메소드와 T라는 이름의 특수한 속성을 가진다.
다차원 배열의 경우 transpose 메소드는 튜플로 축 번호를 받아서 치환한다.

In [116]:
arr=np.arange(21).reshape((7,3))

arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [117]:
arr.T

array([[ 0,  3,  6,  9, 12, 15, 18],
       [ 1,  4,  7, 10, 13, 16, 19],
       [ 2,  5,  8, 11, 14, 17, 20]])

In [120]:
np.dot(arr,arr.T)  #arr*arr.T

array([[   5,   14,   23,   32,   41,   50,   59],
       [  14,   50,   86,  122,  158,  194,  230],
       [  23,   86,  149,  212,  275,  338,  401],
       [  32,  122,  212,  302,  392,  482,  572],
       [  41,  158,  275,  392,  509,  626,  743],
       [  50,  194,  338,  482,  626,  770,  914],
       [  59,  230,  401,  572,  743,  914, 1085]])

In [129]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [128]:
arr.transpose((1,0,2))   
#리스트를 행렬의 한 칸(ex)  1 by 1)으로 생각하고 
#arr.transpose((1,0,dim-1)) 일반적인 transpose라 생각  

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [130]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])